version: '3.8'

services:
  postgresdb:
    image: postgres:16-alpine
    container_name: maqvendas_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-maqvendas}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-maqvendas123}
      POSTGRES_DB: ${POSTGRES_DB:-maqvendas}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-maqvendas} -d ${POSTGRES_DB:-maqvendas}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: {}